<?php
/**
 * Admin asset enqueue.
 *
 * One tiny bundle scoped to the Logs page: registers an `addFilter`
 * callback on `d404.logs.toolbar` that renders the Export-CSV button
 * above the DataViews table.
 *
 * @package DuckDev\FourNotFour\LogsExporter
 */

declare( strict_types = 1 );

namespace DuckDev\FourNotFour\LogsExporter;

// If this file is called directly, abort.
defined( 'ABSPATH' ) || exit;

/**
 * Class Assets
 *
 * @since 1.0.0
 */
final class Assets {

	/**
	 * Map of `screen hook → asset entry name` (no extension).
	 *
	 * Each entry corresponds to a build output produced by
	 * `wp-scripts build` — `<entry>.js` + `<entry>.asset.php`.
	 *
	 * @since 1.0.0
	 */
	const SCREENS = array(
		// Parent plugin's Logs page. The bundle registers the toolbar
		// filter that injects our Export-CSV button. The hook suffix
		// follows the parent's menu structure — Logs lives under the
		// Redirects top-level menu since 4.0.
		'redirects_page_404-to-301-logs' => 'logs-exporter',
	);

	/**
	 * Singleton instance.
	 *
	 * @since 1.0.0
	 * @var self|null
	 */
	private static $instance = null;

	/**
	 * Retrieve the shared instance.
	 *
	 * @since 1.0.0
	 *
	 * @return self
	 */
	public static function instance(): self {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}

		return self::$instance;
	}

	/**
	 * Register the WordPress hooks owned by this class.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public function register(): void {
		// Priority 20 keeps us strictly after the parent's enqueue, so
		// `addFilter` callbacks land before the parent's React tree
		// renders for the first time.
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue' ), 20 );
	}

	/**
	 * Enqueue the matching bundle for the current admin screen.
	 *
	 * @since 1.0.0
	 *
	 * @param string $hook Current admin screen hook.
	 *
	 * @return void
	 */
	public function enqueue( string $hook ): void {
		if ( ! isset( self::SCREENS[ $hook ] ) ) {
			return;
		}

		$entry      = self::SCREENS[ $hook ];
		$asset_file = D404_LOGS_EXPORTER_DIR . 'build/' . $entry . '.asset.php';

		// Build output is generated by `npm run build`; bail quietly on
		// fresh checkouts that haven't been built yet so the admin
		// doesn't fatal.
		if ( ! file_exists( $asset_file ) ) {
			return;
		}

		$asset  = require $asset_file;
		$handle = 'd404-' . $entry;

		wp_enqueue_script(
			$handle,
			D404_LOGS_EXPORTER_URL . 'build/' . $entry . '.js',
			$asset['dependencies'] ?? array(),
			$asset['version'] ?? D404_LOGS_EXPORTER_VERSION,
			true
		);

		// The JS bundle navigates the browser to admin-post.php with a
		// nonce + the current view filters. Both are derived here so
		// the bundle stays free of WP-specific globals.
		wp_localize_script(
			$handle,
			'd404LogsExporter',
			array(
				'endpoint' => admin_url( 'admin-post.php' ),
				'action'   => D404_LOGS_EXPORTER_ACTION,
				'nonce'    => wp_create_nonce( D404_LOGS_EXPORTER_ACTION ),
			)
		);

		wp_set_script_translations( $handle, '404-to-301-logs-exporter' );
	}
}
